# Generated by Django 4.1.5 on 2023-01-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='')),
                ('anons', models.CharField(max_length=60, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Запись')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
