# Generated by Django 4.1.5 on 2023-01-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
    ]
